### ISSUE TITLE
Initial de-duplication / record matching scripts

### ISSUE THREAD

**Issue by pwalsh** [opentrials/warehouse#1]
# Description

As a first pass run over the trial records collected from registers, we want to run some basic matching using unique identifiers and trial titles. The goal of this should be a quick, cheap, simple run to see how far we can get with record matching using the most basic possible techniques.

# Tasks

* [ ]  TBD

**Comment by roll** [comment]
DONE in https://github.com/opentrials/warehouse/pull/9
